### ISSUE TITLE
generate.py errors - how to fix "ValueError" ?

### ISSUE THREAD

**Issue by GenTxt** [hejunqing/tf-char-cnn-lstm#1]
Hi:
I would like to compare output from your version but I am getting this error from generate.py
I do not encounter this error when using mkroutikov's version.
Ubuntu 14, Cuda 7.5, tensorflow 10, python 2.7

Can also generate models using ubuntu 16, cuda 8, tensorflow 11, python 2.7 and 3.5 but same error as below.

Traceback (most recent call last):
  File "generate.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "generate.py", line 78, in main
    dropout=0)
  File "/home/aaron/Desktop/tf-char-cnn-lstm-tf10_cuda7.5/model.py", line 149, in inference_graph
    input_cnn = tdnn(input_embedded, kernels, kernel_features)
  File "/home/aaron/Desktop/tf-char-cnn-lstm-tf10_cuda7.5/model.py", line 112, in tdnn
    output = tf.concat(1, layers)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 697, in concat
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 414, in _concat
    values=values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 753, in _ConcatShape
    (value_shape.ndims, concat_dim))
ValueError: Expected concat_dim in range [0, 1), but got 1

Any suggestions on how to fix the above error so that generate.py runs on tensorflow 10 or 11?

cheers,

**Comment by hejunqing** [comment]
@GenTxt sorry for late reply.
I didn't change and test the code of generate.py
As implied by the warning, the input of the tdnn function should be of 2D, but actually it got a 1D input. You can check your input and make sure the input is of the correct dimension.

**Comment by GenTxt** [comment]
Hello again,

I'm using the included PTB data with your repo. Is there a change I can make to the code so that I can test it properly? Seems strange to include generate.py if it can't be used.

**Comment by hejunqing** [comment]
Sure @GenTxt
